# Generated by Django 6.0.7 on 2026-08-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_primary_admin',
            field=models.BooleanField(default=False, help_text='Protect this account as the primary system administrator.'),
        ),
    ]
